# Generated by Django 5.2 on 2025-12-14 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_room_room_size_check_room_room_price_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gt', models.F('from_date'))), name='booking_days_check'),
        ),
    ]
