# Generated by Django 5.2 on 2025-12-18 15:54

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_booking_booking_days_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
                ('bookings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='booking_price_check'),
        ),
    ]
